<a href="https://colab.research.google.com/github/sriakhilsurapaneni/cv-clomotech-practice/blob/main/day_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
n=[1,2,3,4,5,6,712]
n=np.array(n)
print(n.size,n.shape,n.dtype,n.ndim)

7 (7,) int64 1




age_array = np.array([22, 34, 57, 65, 87, 19, 44])



print(age_array.size,age_array.shape)


In [11]:
n=np.array([x*10 for x in range(1,11)])
print(n.size,n.shape,n.dtype,n.ndim)
print(n)
print(n.reshape(10,1))


10 (10,) int64 1
[ 10  20  30  40  50  60  70  80  90 100]
[[ 10]
 [ 20]
 [ 30]
 [ 40]
 [ 50]
 [ 60]
 [ 70]
 [ 80]
 [ 90]
 [100]]


In [16]:
print(np.linspace(2,8,4))

[2. 4. 6. 8.]


In [38]:
import numpy as np
rn = np.random.default_rng(seed=42)

print(rn.random(5))
rn = np.random.default_rng(seed=42)
print(rn.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]
[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]


In [30]:
import numpy as np
rng=np.random.default_rng(12345)
random_ages=rng.integers(1,101,100)
print(random_ages)


[70 23 79 32 21 80 65 68 99 40 84 34 57 60 22 19 23 68 62 95 71 25 92 95
 74 67 14 10 27 45  8 89 48 70 22 33 12 74 78 23 72  9 40 16 75 35 48 47
 48 27 56 82 50 20  3 13  9 10 13 60 81 86 66 61 34 94 65 73 74 87 71 93
 55 55 26 94 56 50 32 28 64 46 57 67 90 34 69 91 46 26 30 34 63 26 84 36
  7  1  3 63]


In [34]:
print(np.arange(10,101,10,dtype=float).reshape(5,2))

[[ 10.  20.]
 [ 30.  40.]
 [ 50.  60.]
 [ 70.  80.]
 [ 90. 100.]]


In [40]:
a=np.random.default_rng(seed=2022)
a=a.random(9).reshape(3,3)
print(a[:2,:])
print(a[:,0])
print(a[2,1])

[[0.24742606 0.09299006 0.61176337]
 [0.06066207 0.66103343 0.75515778]]
[0.24742606 0.06066207 0.1108689 ]
0.04305584439252108


In [37]:

ages = np.array([5, 10, 15, 19, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])

youth_ages=ages[1:4]
adult_ages=ages[4:14]
senior_ages=ages[14:]
print(youth_ages)
print(adult_ages)
print(senior_ages)

[10 15 19]
[20 25 30 35 40 45 50 55 60 65]
[70 75 80]


In [41]:
a=np.random.default_rng(seed=2022)
a=a.random(9).reshape(3,3)
a=a[:2]
a=a-1


In [44]:
x=np.random.default_rng(seed=2022)
random_ages=x.integers(1,101,100).reshape(2,50)
print(random_ages)
teens = random_ages[(random_ages >= 13) & (random_ages <= 19)]
print(teens.shape)

[[ 71  25  75  10  19  62  94   7   7  67  87  76  83  12  57   5  10  42
   88  99  39  97   1  26  63  56  37  25   9  33  32  90  35  95  90  73
    5  93  72 100   3  25  63   7  46  95  64  66  71  33]
 [ 10   9   6  22  89   9  59   6  97  21  12   8  87  35  55  14   3  59
   91   1  85  30  16  20  25  15  13  99  15  29  47  47  12  29  42  96
   20  60  29  50  42  70  67  43  66   1  81  70  54  65]]
(6,)


import numpy as np


ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])

print(np.arange(0,10,1)[ages>=18])




In [3]:

import numpy as np

# Provided array of ages
ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])

# Use NumPy's where function to find indices of ages that are 18 or older
adult_ages = np.where(ages >= 18)

# Output the indices
print("Ages of adults:", adult_ages)

Ages of adults: (array([0, 3, 4, 5, 6, 8, 9]),)


In [11]:
prices=np.array([5.99,6.99,22.49,99.99,4.99,49.99])
prices.sort()
prices=prices[-3::]
print(prices)
prices.mean()
prices.max()
np.median(prices)
np.unique(prices)



[22.49 49.99 99.99]


array([22.49, 49.99, 99.99])